db_name = "tf_creating_rds"
db_engine = "mysql"
db_engine_version = "8.0"
db_instance_class = "db.t3.micro"
db_username = "<username>" # Replace with actual username
db_password = "<password>" # Replace with actual password
db_group_name = "default.mysql8.0"
db_subnet_group_name = "default"
vpc_security_group_ids = ["sg-12345678"] # Example security group ID, replace with actual